name: generate circuit board

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: generate circuit-board.svg
        run: node scripts/pcb-generator.js /tmp/circuit-board.svg
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push circuit-board.svg to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin output
          git checkout output
          cp /tmp/circuit-board.svg .
          git add circuit-board.svg
          git diff --staged --quiet || git commit -m "Update circuit-board [automated]"
          git push origin output
